@php($editing = $member !== null)
@extends('layouts.app', ['title' => $editing ? 'Benutzer bearbeiten' : 'Benutzer hinzufügen', 'heading' => $editing ? $member->name : 'Benutzer hinzufügen', 'eyebrow' => $tenant->name, 'tenant' => $tenant])
@section('content')
<form class="panel" method="post" action="{{ $editing ? route('taxi-control.tenant.users.update',['tenant'=>$tenant->slug,'user'=>$member->id]) : route('taxi-control.tenant.users.store',['tenant'=>$tenant->slug]) }}">@csrf @if($editing) @method('PUT') @endif
@if(!$editing)<div class="grid two"><label class="field"><span>Name</span><input name="name" value="{{ old('name') }}" required></label><label class="field"><span>E-Mail</span><input type="email" name="email" value="{{ old('email') }}" required></label></div><label class="field"><span>Initiales Passwort</span><input type="password" name="password"><small>Nur erforderlich, wenn die E-Mail noch kein globales Taxi-Control-Konto besitzt.</small></label>@else<div class="info-box"><strong>{{ $member->email }}</strong><span>Globale Kontodaten werden hier bewusst nicht verändert.</span></div><label class="field"><span>Status im Mandanten</span><select name="status"><option value="active" @selected(old('status',$member->pivot->status)==='active')>Aktiv</option><option value="inactive" @selected(old('status',$member->pivot->status)==='inactive')>Inaktiv</option></select></label>@endif
<div class="panel-header top-gap"><div><span class="eyebrow">Zugriff</span><h2>Rollen</h2></div></div><div class="check-grid">@foreach($roles as $role)<label class="permission-check"><input type="checkbox" name="roles[]" value="{{ $role->id }}" @checked(in_array($role->id, old('roles',$selectedRoles)))><span><strong>{{ $role->name }}</strong><small>{{ $role->description }}</small></span></label>@endforeach</div>
<div class="form-actions top-gap"><a class="btn" href="{{ route('taxi-control.tenant.users.index',['tenant'=>$tenant->slug]) }}">Zurück</a><button class="btn btn-primary" type="submit">Speichern</button></div></form>
@if($editing)<section class="panel danger-zone top-gap"><h2>Aus Mandant entfernen</h2><p>Das globale Benutzerkonto bleibt bestehen; nur Mitgliedschaft, Rollen und Einzelrechte dieses Mandanten werden entfernt.</p><form method="post" action="{{ route('taxi-control.tenant.users.destroy',['tenant'=>$tenant->slug,'user'=>$member->id]) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Benutzer entfernen</button></form></section>@endif
@endsection
