@php($editing = $member !== null)
@extends('layouts.app', ['title' => $editing ? 'Benutzer bearbeiten' : 'Benutzer hinzufügen', 'heading' => $editing ? $member->name : 'Benutzer hinzufügen', 'eyebrow' => $tenant->name, 'tenant' => $tenant])
@section('content')
<form class="panel" method="post" action="{{ $editing ? route('taxi-control.tenant.users.update',['tenant'=>$tenant->slug,'user'=>$member->id]) : route('taxi-control.tenant.users.store',['tenant'=>$tenant->slug]) }}">@csrf @if($editing) @method('PUT') @endif
@if(!$editing)<div class="grid two"><label class="field"><span>Name</span><input name="name" value="{{ old('name') }}" required></label><label class="field"><span>E-Mail</span><input type="email" name="email" value="{{ old('email') }}" required></label></div><label class="field"><span>Initiales Passwort</span><input type="password" name="password"><small>Nur erforderlich, wenn die E-Mail noch kein globales Taxi-Control-Konto besitzt.</small></label>@else<div class="info-box"><strong>{{ $member->email }}</strong><span>Globale Kontodaten werden hier bewusst nicht verändert.</span></div><label class="field"><span>Status im Mandanten</span><select name="status"><option value="active" @selected(old('status',$member->pivot->status)==='active')>Aktiv</option><option value="inactive" @selected(old('status',$member->pivot->status)==='inactive')>Inaktiv</option></select></label>@endif
<label class="permission-check top-gap"><input type="checkbox" name="is_owner" value="1" @checked(old('is_owner',$editing ? (bool)$member->pivot->is_owner : false))><span><strong>Mandanten-Eigentümer</strong><small>Der letzte aktive Eigentümer kann nicht entfernt oder deaktiviert werden.</small></span></label>
<div class="panel-header top-gap"><div><span class="eyebrow">Zugriff</span><h2>Rollen</h2><p>Mehrere Rollen sind möglich.</p></div></div><div class="check-grid">@foreach($roles as $role)<label class="permission-check"><input type="checkbox" name="roles[]" value="{{ $role->id }}" @checked(in_array($role->id, old('roles',$selectedRoles)))><span><strong>{{ $role->name }}</strong><small>{{ $role->description }}</small></span></label>@endforeach</div>
<div class="panel-header top-gap"><div><span class="eyebrow">Feinsteuerung</span><h2>Direkte Einzelrechte</h2><p>„Rollen übernehmen“ verwendet die Rollenberechtigungen. „Verweigern“ hat Vorrang vor jeder Rollenfreigabe.</p></div></div>
@foreach($permissionsByModule as $module=>$permissions)<div class="top-gap"><strong>{{ ucfirst($module) }}</strong><div class="table-wrap"><table><thead><tr><th>Berechtigung</th><th>Datenbereich</th><th>Einzelrecht</th></tr></thead><tbody>@foreach($permissions as $permission)@php($value=old('permission_overrides.'.$permission->id,$permissionOverrides[$permission->id] ?? 'inherit'))<tr><td><strong>{{ $permission->label }}</strong><br><code>{{ $permission->key }}</code></td><td>{{ $permission->data_scope }}@if($permission->sensitive_field)<br><small>Sensibles Feld: {{ $permission->sensitive_field }}</small>@endif</td><td><select name="permission_overrides[{{ $permission->id }}]"><option value="inherit" @selected($value==='inherit')>Rollen übernehmen</option><option value="allow" @selected($value==='allow')>Zusätzlich erlauben</option><option value="deny" @selected($value==='deny')>Verweigern</option></select></td></tr>@endforeach</tbody></table></div></div>@endforeach
<div class="form-actions top-gap"><a class="btn" href="{{ route('taxi-control.tenant.users.index',['tenant'=>$tenant->slug]) }}">Zurück</a><button class="btn btn-primary" type="submit">Speichern</button></div></form>
@if($editing)<section class="panel danger-zone top-gap"><h2>Aus Mandant entfernen</h2><p>Das globale Benutzerkonto bleibt bestehen; nur Mitgliedschaft, Rollen und Einzelrechte dieses Mandanten werden entfernt.</p><form method="post" action="{{ route('taxi-control.tenant.users.destroy',['tenant'=>$tenant->slug,'user'=>$member->id]) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Benutzer entfernen</button></form></section>@endif
@endsection
