@php($editing = $tenant->exists)
@extends('layouts.app', ['title' => $editing ? 'Mandant bearbeiten' : 'Mandant anlegen', 'heading' => $editing ? $tenant->name : 'Neuer Mandant', 'eyebrow' => 'SaaS-Control-Center'])
@section('content')
@if($editing)<div class="toolbar"><div><p class="muted">Mandant-ID {{ $tenant->id }} · /taxi-control/{{ $tenant->slug }}</p></div><div class="form-actions"><a class="btn" href="{{ route('taxi-control.superadmin.tenants.features.edit',$tenant) }}">Feature-Overrides</a><a class="btn btn-primary" href="{{ route('taxi-control.tenant.dashboard',['tenant'=>$tenant->slug]) }}">Mandant öffnen</a></div></div>@endif
<form class="panel {{ $editing?'top-gap':'' }}" method="post" action="{{ $editing ? route('taxi-control.superadmin.tenants.update', $tenant) : route('taxi-control.superadmin.tenants.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="panel-header"><div><span class="eyebrow">Stammdaten</span><h2>Taxiunternehmen</h2><p>Der Slug bestimmt den sichtbaren Mandantenpfad. Die serverseitige Isolation erfolgt unabhängig davon über tenant_id.</p></div></div>
<div class="grid two"><label class="field"><span>Anzeigename</span><input name="name" value="{{ old('name', $tenant->name) }}" required></label><label class="field"><span>Rechtlicher Firmenname</span><input name="legal_name" value="{{ old('legal_name', $tenant->legal_name) }}"></label><label class="field"><span>Slug</span><input name="slug" value="{{ old('slug', $tenant->slug) }}" placeholder="wird aus dem Namen erzeugt"></label><label class="field"><span>Abrechnungs-E-Mail</span><input type="email" name="billing_email" value="{{ old('billing_email', $tenant->billing_email) }}"></label><label class="field"><span>Status</span><select name="status"><option value="trial" @selected(old('status',$tenant->status)==='trial')>Testphase</option><option value="active" @selected(old('status',$tenant->status)==='active')>Aktiv</option><option value="suspended" @selected(old('status',$tenant->status)==='suspended')>Gesperrt</option><option value="cancelled" @selected(old('status',$tenant->status)==='cancelled')>Beendet</option></select></label><label class="field"><span>SaaS-Paket</span><select name="saas_package_id"><option value="">Kein Paket</option>@foreach($packages as $package)<option value="{{ $package->id }}" @selected((string)old('saas_package_id', $subscription->saas_package_id ?? '') === (string)$package->id)>{{ $package->name }}</option>@endforeach</select></label><input type="hidden" name="timezone" value="Europe/Berlin"><input type="hidden" name="locale" value="de"></div>
<div class="form-actions"><a class="btn" href="{{ route('taxi-control.superadmin.tenants.index') }}">Zurück</a><button class="btn btn-primary" type="submit">{{ $editing ? 'Änderungen speichern' : 'Mandant anlegen' }}</button></div></form>
@if($editing)<section class="panel danger-zone top-gap"><div class="panel-header"><div><span class="eyebrow">Gefahrenbereich</span><h2>Mandant löschen</h2><p>Alle abhängigen SaaS-Daten werden über Fremdschlüssel konsistent mit entfernt. Diese Aktion ist nicht rückgängig zu machen.</p></div></div><form method="post" action="{{ route('taxi-control.superadmin.tenants.destroy', $tenant) }}">@csrf @method('DELETE')<label class="field"><span>Zur Bestätigung Slug „{{ $tenant->slug }}“ eingeben</span><input name="confirmation" required></label><button class="btn btn-danger" type="submit">Mandant endgültig löschen</button></form></section>@endif
@endsection
