@php($editing=$package->exists)
@extends('layouts.app', ['title'=>$editing?'Paket bearbeiten':'Paket anlegen','heading'=>$editing?$package->name:'Neues SaaS-Paket','eyebrow'=>'SaaS-Control-Center'])
@section('content')
<form class="panel" method="post" action="{{ $editing ? route('taxi-control.superadmin.packages.update',$package) : route('taxi-control.superadmin.packages.store') }}">@csrf @if($editing)@method('PUT')@endif
<div class="grid two"><label class="field"><span>Name</span><input name="name" value="{{ old('name',$package->name) }}" required></label><label class="field"><span>Slug</span><input name="slug" value="{{ old('slug',$package->slug) }}"></label><label class="field"><span>Monatspreis</span><input type="number" step="0.01" min="0" name="price_monthly" value="{{ old('price_monthly',$package->price_monthly) }}"></label><label class="field"><span>Jahrespreis</span><input type="number" step="0.01" min="0" name="price_yearly" value="{{ old('price_yearly',$package->price_yearly) }}"></label><label class="field"><span>Benutzerlimit</span><input type="number" min="1" name="limit_users" value="{{ old('limit_users',$package->limits['users'] ?? '') }}"><small>Leer = unbegrenzt</small></label><label class="field"><span>Fahrzeuglimit</span><input type="number" min="1" name="limit_vehicles" value="{{ old('limit_vehicles',$package->limits['vehicles'] ?? '') }}"><small>Leer = unbegrenzt</small></label><label class="field"><span>Status</span><select name="is_active"><option value="1" @selected(old('is_active',$package->is_active)!==false)>Aktiv</option><option value="0" @selected((string)old('is_active',$package->is_active)==='0')>Inaktiv</option></select></label></div>
<label class="field"><span>Beschreibung</span><textarea name="description" rows="4">{{ old('description',$package->description) }}</textarea></label>
<div class="panel-header top-gap"><div><span class="eyebrow">Funktionsumfang</span><h2>Features</h2></div></div><div class="check-grid">@php($selected=old('features',$editing?$package->features->pluck('id')->all():[])) @foreach($features as $feature)<label class="permission-check"><input type="checkbox" name="features[]" value="{{ $feature->id }}" @checked(in_array($feature->id,$selected))><span><strong>{{ $feature->name }}</strong><small>{{ $feature->key }}</small></span></label>@endforeach</div>
<div class="form-actions top-gap"><a class="btn" href="{{ route('taxi-control.superadmin.packages.index') }}">Zurück</a><button class="btn btn-primary">Speichern</button></div></form>
@if($editing)<section class="panel danger-zone top-gap"><h2>Paket löschen</h2><p>Nur möglich, solange kein Mandant das Paket verwendet.</p><form method="post" action="{{ route('taxi-control.superadmin.packages.destroy',$package) }}">@csrf @method('DELETE')<button class="btn btn-danger">Paket löschen</button></form></section>@endif
@endsection
