@php($editing = $role->exists)
@extends('layouts.app', ['title' => $editing ? 'Rolle bearbeiten' : 'Rolle anlegen', 'heading' => $editing ? $role->name : 'Neue Rolle', 'eyebrow' => $tenant->name, 'tenant' => $tenant])
@section('content')
<form class="panel" method="post" action="{{ $editing ? route('taxi-control.tenant.roles.update',['tenant'=>$tenant->slug,'role'=>$role->id]) : route('taxi-control.tenant.roles.store',['tenant'=>$tenant->slug]) }}">@csrf @if($editing) @method('PUT') @endif
<div class="grid two"><label class="field"><span>Name</span><input name="name" value="{{ old('name',$role->name) }}" @disabled($role->is_system) required></label><label class="field"><span>Slug</span><input name="slug" value="{{ old('slug',$role->slug) }}" @disabled($role->is_system) placeholder="wird automatisch erzeugt"></label></div><label class="field"><span>Beschreibung</span><textarea name="description" rows="3">{{ old('description',$role->description) }}</textarea></label>
<div class="panel-header top-gap"><div><span class="eyebrow">Granulare Rechte</span><h2>Berechtigungen</h2></div></div>
<div class="permission-modules">@foreach($permissionsByModule as $module => $permissions)<section class="permission-module"><h3>{{ ucfirst($module) }}</h3><div class="check-grid">@foreach($permissions as $permission)<label class="permission-check"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked(in_array($permission->id, old('permissions',$selectedPermissions)))><span><strong>{{ $permission->label }}</strong><small>{{ $permission->key }}</small></span></label>@endforeach</div></section>@endforeach</div>
<div class="form-actions top-gap"><a class="btn" href="{{ route('taxi-control.tenant.roles.index',['tenant'=>$tenant->slug]) }}">Zurück</a><button class="btn btn-primary" type="submit">Speichern</button></div></form>
@if($editing && !$role->is_system)<section class="panel danger-zone top-gap"><h2>Rolle löschen</h2><form method="post" action="{{ route('taxi-control.tenant.roles.destroy',['tenant'=>$tenant->slug,'role'=>$role->id]) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Rolle löschen</button></form></section>@endif
@endsection
